# Generated by Django 3.2.7 on 2021-10-30 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('time_date', models.DateTimeField()),
                ('likes', models.PositiveIntegerField()),
                ('owner', models.ManyToManyField(blank=True, related_name='post_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
