# Generated by Django 3.2.7 on 2021-10-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20211030_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.CharField(default='', max_length=500),
        ),
    ]
