# Generated by Django 3.2.7 on 2021-10-31 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20211030_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
