# Generated by Django 3.2.7 on 2021-11-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211108_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
