# Generated by Django 3.2.7 on 2021-11-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20211108_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
